-- 코드를 입력하세요
-- 자동차 ID / 자동차 종류 / 일일 대여 요금(원) / 자동차 옵션 리스트
-- 대여 기록 ID, 자동차 ID, 대여 시작일, 대여 종료일
-- 요금 할인 정책 ID, 자동차 종류, 대여 기간 종류, 할인율(%)
SELECT 
    C.CAR_ID,
    C.CAR_TYPE,
    TRUNC(C.DAILY_FEE * (100 - P.DISCOUNT_RATE) / 100 * 30) AS FEE
FROM
    CAR_RENTAL_COMPANY_CAR C
    LEFT OUTER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H 
    ON C.CAR_ID = H.CAR_ID AND H.START_DATE <= DATE '2022-11-30' AND H.END_DATE >= DATE '2022-11-01'
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE AND P.DURATION_TYPE = '30일 이상'
WHERE 
    C.CAR_TYPE IN ('세단', 'SUV')
    AND H.CAR_ID IS NULL
    AND TRUNC(C.DAILY_FEE * (100 - P.DISCOUNT_RATE) / 100 * 30) >= 500000
  AND TRUNC(C.DAILY_FEE * (100 - P.DISCOUNT_RATE) / 100 * 30) < 2000000
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;