-- 코드를 입력하세요
SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
FROM REST_INFO R 
RIGHT OUTER JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) FAVORITES
                  FROM REST_INFO
                  GROUP BY FOOD_TYPE) MAXR ON R.FOOD_TYPE = MAXR.FOOD_TYPE AND R.FAVORITES = MAXR.FAVORITES
ORDER BY R.FOOD_TYPE DESC