-- 코드를 입력하세요
-- USER_INFO
-- USER_ID, GENDER, AGE, JOINED
-- 회원 ID, 성별, 나이, 가입일
-- GENDER 0 M / 1 W

-- ONLINE_SALE
-- ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
-- 상품 판매 ID, 회원 ID, 상품 ID, 판매량, 판매일
-- USER_ID, PRODUCT_ID, SALES_DATE -> PRIME
SELECT 
    EXTRACT(YEAR FROM O.SALES_DATE) YEAR, 
    EXTRACT(MONTH FROM O.SALES_DATE) MONTH, 
    U.GENDER GENDER, 
    COUNT(DISTINCT O.USER_ID) USERS
FROM 
    USER_INFO U JOIN 
    ONLINE_SALE O ON U.USER_ID = O.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY EXTRACT(YEAR FROM O.SALES_DATE), EXTRACT(MONTH FROM O.SALES_DATE), U.GENDER
ORDER BY YEAR, MONTH, GENDER
