-- 코드를 입력하세요
SELECT 
    C.CAR_ID, 
    TO_CHAR(ROUND(AVG(C.END_DATE - C.START_DATE + 1), 1), 'FM9990.0') AVERAGE_DURATION
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY C
GROUP BY 
    C.CAR_ID
HAVING 
    AVG(C.END_DATE - C.START_DATE + 1) >= 7
ORDER BY 
    ROUND(AVG(C.END_DATE - C.START_DATE + 1), 1) DESC, 
    C.CAR_ID DESC