SELECT 
    HC.HISTORY_ID,
    CASE 
        WHEN P.PLAN_ID IS NOT NULL 
            THEN HC.DAILY_FEE * HC.DAYS * (100 - P.DISCOUNT_RATE) / 100
        ELSE HC.DAILY_FEE * HC.DAYS
    END FEE
                
FROM (SELECT H.HISTORY_ID, C.CAR_TYPE, C.DAILY_FEE, H.END_DATE - H.START_DATE + 1 DAYS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID AND C.CAR_TYPE = '트럭') HC
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
    ON HC.CAR_TYPE = P.CAR_TYPE 
    AND (CASE
         WHEN HC.DAYS < 7 THEN '1일 이상'
         WHEN HC.DAYS < 30 THEN '7일 이상'
         WHEN HC.DAYS < 90 THEN '30일 이상'
         ELSE '90일 이상'
        END) = P.DURATION_TYPE
ORDER BY FEE DESC, HC.HISTORY_ID DESC