-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, TO_CHAR(DATE_OF_BIRTH, 'yyyy-mm-dd') DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE TLNO is not null AND EXTRACT(MONTH FROM DATE_OF_BIRTH) = '03' and GENDER = 'W'
ORDER BY MEMBER_ID;