-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD B LEFT OUTER JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
GROUP BY U.USER_ID, U.NICKNAME, B.STATUS
HAVING B.STATUS LIKE 'DONE' AND SUM(B.PRICE) >= 700000
ORDER BY TOTAL_SALES