-- 코드를 입력하세요
-- 회원 ID, 회원 이름, 회원 연락처, 성별, 생년월일
-- 리뷰 ID, 식당 ID, 회원 ID, 점수, 리뷰 텍스트, 리뷰 작성일
SELECT P.MEMBER_NAME, R.REVIEW_TEXT, TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD') REVIEW_DATE
FROM MEMBER_PROFILE P 
LEFT JOIN REST_REVIEW R ON P.MEMBER_ID = R.MEMBER_ID

WHERE P.MEMBER_ID = (SELECT MEMBER_ID
FROM(
    SELECT MEMBER_ID, COUNT(REVIEW_ID) ALL_REVIEWS
    FROM REST_REVIEW 
    GROUP BY MEMBER_ID
    ORDER BY ALL_REVIEWS DESC)
WHERE ROWNUM = 1)
ORDER BY REVIEW_DATE ASC, R.REVIEW_TEXT ASC