-- 코드를 입력하세요
-- HISTORY_ID           CAR_ID	    START_DATE	END_DATE
-- 자동차 대여 기록 ID     자동차 ID,    대여 시작일, 대여 종료일
SELECT EXTRACT(MONTH FROM START_DATE) MONTH, CAR_ID, COUNT(HISTORY_ID) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE EXTRACT(MONTH FROM START_DATE) BETWEEN '8' AND '10'
    AND CAR_ID IN (SELECT C.CAR_ID
                 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
                 WHERE START_DATE >= TO_DATE('2022-08', 'YYYY-MM') AND START_DATE < TO_DATE('2022-11', 'YYYY-MM')
                 GROUP BY C.CAR_ID 
                 HAVING COUNT(C.HISTORY_ID) >= 5)
GROUP BY EXTRACT(MONTH FROM START_DATE), CAR_ID
HAVING COUNT(HISTORY_ID) != 0
ORDER BY MONTH ASC, CAR_ID DESC;

