-- 코드를 입력하세요
SELECT FP.CATEGORY, MAXFP.MAX_PRICE, FP.PRODUCT_NAME
FROM FOOD_PRODUCT FP 
RIGHT OUTER JOIN (SELECT CATEGORY, MAX(PRICE) MAX_PRICE
                 FROM FOOD_PRODUCT 
                 GROUP BY CATEGORY
                 HAVING CATEGORY IN ('과자', '국', '김치', '식용유') ) MAXFP ON 
                 FP.CATEGORY = MAXFP.CATEGORY AND FP.PRICE = MAXFP.MAX_PRICE
ORDER BY MAXFP.MAX_PRICE DESC